version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html/
    image: ssjatesz/dpdtest

  composer:
    image: composer:1.9
    command: [ "composer", "install" ]
    volumes:
      - ./:/app


